apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: demo
spec:
  ports:
    - name: "3306"
      port: 3306
      nodePort: 30306
      targetPort: 3306
    - name: "8080"
      port: 8080
      nodePort: 30080
      targetPort: 8080
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: mysql
  type: NodePort
status:
  loadBalancer: {}
